version: '2'
networks:
  default:
    external:
      name: localEnvNetwork
services:
    mysql:
        image: mysql
        command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password --innodb_flush_log_at_trx_commit=0 --sync-binlog=0
        restart: always
        ports:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=Catch22
